# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f78864721ad43931d5585acd4f507bb38e0ec5c6ba02b7fb6c9cd5e76bb42c7654aefa51e9e06b9e00d89bae7447cad22577cbcfd36973a98834744f2ce9a472
  s3_access_key_id: AKIAJ2UOFG5SPFPIPAHQ
  s3_secret_access_key: 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
test:
  secret_key_base: 69084ad2bcdf43e9830592203cb62cd413c554267c5ba3903833c492197b4636ec9b6a55ae2e2e0caa245dc77c3b7b802d08d175fdeedbe2d47f25e1ac6cff20
  s3_access_key_id: AKIAJ2UOFG5SPFPIPAHQ
  s3_secret_access_key: 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
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>


# sk_test_JILVhXXeqARyQnfShtpEmbxj

# pk_test_1knJauQbsbWYsMDJsKorOq39